# Generated by Django 5.1.7 on 2025-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
